#!/usr/bin/env bash
set -e

# Work from this scripts location
cd "$(dirname "$0")"

# Back out of an update if the compose stack is already running.
if ! [[ $(docker compose ps -q | wc -l) = "0" ]]; then
        echo 'Project Zomboid server currently running. Run `docker compose down` before updating.'
        exit 1
fi

# Load the .env file to know the `SERVER_FILES` and `DATA_FILES` values
source .env
# Ensure each mounted folder exists and is owned by `1000:1000`.
for dir in "$SERVER_FILES" "$DATA_FILES"; do
        mkdir -p "$dir"
        if [[ $(stat --format '%u:%g' "$dir") != '1000:1000' ]]; then
                echo "Requires root to fixup ownership of $dir"
                sudo chown 1000:1000 -R "$dir"
        fi
done

# Path inside the container to `steamcmd`, I wish it was just in PATH...
STEAMCMD_PATH=/home/steam/steamcmd/steamcmd.sh
docker compose run --rm project-zomboid $STEAMCMD_PATH +runscript /steamcmd-script
echo 'Project Zomboid server updated. Run `docker compose up` to start the server'